# Generated by Django 5.0.7 on 2024-07-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('footer_text', models.CharField(max_length=50, verbose_name='متن فوتر')),
                ('logo', models.ImageField(upload_to='homepage', verbose_name='تصویر')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('twitter', models.URLField(verbose_name='توییتر')),
                ('instagram', models.URLField(verbose_name='اینستاگرام')),
                ('linkedin', models.URLField(verbose_name='لینکدین')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'صفحه اصلی',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'سازمان', 'verbose_name_plural': 'سازمان ها'},
        ),
    ]
