# Generated by Django 5.0.7 on 2024-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_homepage_footer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='متن')),
                ('image', models.ImageField(upload_to='slider', verbose_name='عکس')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر\u200cها',
            },
        ),
    ]
