# Generated by Django 5.0.7 on 2024-07-31 17:59

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='google_map',
            field=models.TextField(null=True, verbose_name='گوگل مپ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_content',
            field=tinymce.models.HTMLField(null=True, verbose_name='محتوای صفحه اصلی'),
        ),
    ]
