# Generated by Django 5.0.7 on 2024-08-01 14:12

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('start_date', models.CharField(max_length=50, verbose_name='تاریخ تاسیس')),
                ('image', models.ImageField(upload_to='aboutpage', verbose_name='تصویر')),
                ('content', tinymce.models.HTMLField(null=True, verbose_name='محتوای صفحه ')),
            ],
            options={
                'verbose_name': 'صفحه درباره\u200cما',
                'verbose_name_plural': 'صفحه درباره\u200cما',
            },
        ),
    ]
