# Generated by Django 5.0.7 on 2024-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='founder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='مدیر عامل'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره تماس'),
        ),
    ]
