# Generated by Django 5.0.7 on 2024-08-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_company_founder_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.URLField(default='www.google.com', verbose_name='لینک سایت'),
            preserve_default=False,
        ),
    ]
