# Generated by Django 5.0.7 on 2024-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_company_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک سایت'),
        ),
    ]
