# Generated by Django 5.0.7 on 2024-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_aboutpage_founder_aboutpage_link_aboutpage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='subtext',
            field=models.CharField(default=1, max_length=50, verbose_name='سابتکست'),
            preserve_default=False,
        ),
    ]
