# Generated by Django 5.0.7 on 2024-08-03 22:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_slider_subtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='subtext',
            field=tinymce.models.HTMLField(verbose_name='سابتکست'),
        ),
    ]
